services:
  api:
    # The image will be pulled from AWS ECR, injected via environment variable
    image: ${IMAGE_NAME}
    restart: always
    ports:
      # Map EC2 port 80 -> container port 8000
      - "80:8000"
    env_file:
      - ./.env.prod
    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/v1/health/live || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"