services:
  api:
    image: ${IMAGE_NAME}
    restart: always
    ports:
      - "80:8000"  # Expose FastAPI on port 80
    env_file:
      - ./.env.prod
    command: >
      sh -c "
      echo 'Running Alembic migrations...' &&
      alembic upgrade head &&
      echo 'Starting FastAPI...' &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/v1/health/live || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
