services:
  api:
    image: ${IMAGE_NAME}
    restart: always
    ports:
      - "80:8000"  # Expose FastAPI on port 80
    env_file:
      - ./.env.prod
    command: ./entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/v1/health/live || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
