"""Initial migration

Revision ID: be05f246ceeb
Revises: 
Create Date: 2025-09-09 08:22:40.428743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be05f246ceeb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=True)
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('two_fa_enabled', sa.Boolean(), nullable=False,server_default=sa.text('false')))
    op.add_column('users', sa.Column('two_fa_secret', sa.String(length=32), nullable=True))
    op.drop_column('users', 'twofa_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('twofa_secret', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_column('users', 'two_fa_secret')
    op.drop_column('users', 'two_fa_enabled')
    op.drop_column('users', 'is_verified')
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
